### ISSUE TITLE
Wonder how to install this programme successfully?

### ISSUE THREAD

**Issue by code-isnot-cold** [ShuHuang/batterydataextractor#1]
I installed this programme by using "python setup.py install" in the cmd, but both python3.7 and python3.8 failed.
I would appreciate it if you could contact me. Email:pengwj@dicp.ac.cn

**Comment by ShuHuang** [comment]
Hi, have you tried "pip install batterydataextractor" instead?

**Comment by code-isnot-cold** [comment]
> Hi, have you tried "pip install batterydataextractor" instead?
Sry that my late reply . I have installed successfully by learning from CSDN, and I found it's probably caused by the operating system (MAC and WINDOWS).

**Comment by ghost** [comment]
Hi!

I was also running problems into installing the app. It looked like package versions from requirements.txt are not matching exactly with the desirable packages. For example, _token-classification_ appears only in the very recent transformers version, however requirements.txt pointing to way older packages also.

Thanks
