### ISSUE TITLE
missing import

### ISSUE THREAD

**Issue by ghost** [ShuHuang/batterydataextractor#2]
Hi!

With pip3 install, the following line was missing from the local package:

[link](https://github.com/ShuHuang/batterydataextractor/blob/733c2b2d7c157ba0283fdb6197e91cd1585ed15a/batterydataextractor/nlp/cem.py#L9)

Thanks,
R

**Comment by code-isnot-cold** [comment]
Two methods for you:
1. Pycharm-terminal-cd "your env location"-pip install transformers
2. Anaconda-Environment-"open your env's terminal"-pip install transformers
Good wishes

**Comment by ghost** [comment]
Hi!

The problem is still, that this line is not included in the code.

**Comment by code-isnot-cold** [comment]
What do "not included in the code" specificly mean? It means that line is not quoted or you don't have the "transformers package" ?

**Comment by ShuHuang** [comment]
Hi, problems fixed. Please use "pip install -U batterydataextractor" to download the latest version.
