### ISSUE TITLE
Confused about "scrape" code

### ISSUE THREAD

**Issue by code-isnot-cold** [ShuHuang/batterydataextractor#3]
Hallo, I'm a little confused about your code.
Can u explain what the three parameters mean? 
Thanks so much!

![code](https://user-images.githubusercontent.com/105880123/200787721-be1c4e68-c57f-4c77-9d8c-85e2eb64a122.png)

**Comment by ShuHuang** [comment]
Hi, the "show" parameter gives the number of publications per query, while the "offset" represents the starting position.
Check details here: https://dev.elsevier.com/documentation/ScienceDirectSearchAPI.wadl
